# Generated by Django 6.0.4 on 2026-04-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(blank=True, help_text='Мәтін мазмұны немесе видео/файл сілтемесі'),
        ),
    ]
