# Generated by Django 6.0.4 on 2026-04-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_material_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file_upload',
            field=models.FileField(blank=True, help_text='Жүктелген файл (тек FILE типі үшін)', null=True, upload_to='materials/'),
        ),
    ]
