# Generated by Django 6.0.4 on 2026-04-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_lessoncompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text='Оқушының жинаған ұпайы'),
        ),
    ]
