# Generated by Django 6.0.4 on 2026-04-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, help_text='Материал сипаттамасы', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(blank=True, help_text='Материал атауы', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(blank=True, help_text='Мәтін мазмұны немесе видео/файл сілтемесі / ойын түрі'),
        ),
    ]
