# Generated by Django 6.0.4 on 2026-04-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_material_description_material_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Ойын сұрақтары мен баптаулары (JSON форматта)'),
        ),
    ]
