# Generated by Django 6.0.4 on 2026-04-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_material_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Мұғалім'), ('STUDENT', 'Оқушы'), ('ADMIN', 'Админ')], default='STUDENT', max_length=10),
        ),
    ]
