# Generated by Django 6.0.4 on 2026-04-28 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Тақырыптық тест үшін', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thematic_tests', to='education.section'),
        ),
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(blank=True, help_text='Мәтін мазмұны / Видео сілтемесі / Ойын-Тест түрі'),
        ),
        migrations.AlterField(
            model_name='material',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Сұрақтар, жауаптар және ТҮСІНДІРМЕЛЕР (JSON)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='education.lesson'),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Мәтін'), ('VIDEO', 'Видео'), ('FILE', 'Файл'), ('GAME', 'Ойын (Optional)'), ('TEST', 'Тест (Mandatory)')], max_length=10),
        ),
    ]
