# Generated by Django 6.0.4 on 2026-04-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_material_section_alter_material_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Сұрақтар мен түсіндірмелер (JSON)'),
        ),
    ]
